### ISSUE TITLE
Unable to download EXE

### ISSUE THREAD

**Issue by PhilBSG** [br-automation-com/mapp-Framework#13]
Hi B&R Framework Team!

Microsoft Edge will not allow the download of the released exe's to complete. The error in edge reports as the exe isn't commonly downloaded make sure you trust... See attached image. It appears as the owner you can report this as a trusted file. The current work around is use chrome or another browser but not all users will be able to do this. 

![image](https://github.com/br-automation-com/mapp-Framework/assets/147527531/4978bb7c-b51c-4111-b13a-f3d68db99fa7)
 

Best, 

Phil Brown

**Comment by PhilBSG** [comment]
Hi Brittany!

In this case even though I am an admin I cannot do this. I am sure there is some IT work around but its likely not going to be possible for security reasons. 

Screenshot of what that button looks like on our end. 
![image](https://github.com/br-automation-com/mapp-Framework/assets/147527531/b14914e9-3eaa-4d1a-b68d-ea4795c29832)

**Comment by langstonb** [comment]
Gotcha - I have reported it as safe to Microsoft, so let's see if it improves over time. In the meantime, please proceed with another browser. 

And if anyone else reading this runs into this problem and another browser is not an option, please let us know and we can share the .exe with you directly!
